name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: set up python
        uses: actions/setup-python@v1
        with:
         python-version: "3.7"
      - name: install backend
        run: cd backend && python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: python3 -m backend.api, npm start
          wait-on: http://localhost:3000
      - name: change heroku buildpack to nodejs
        run: heroku buildpacks:set heroku/nodejs
      - name: deploy to prod frontend
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: dashboard-for-errors
          heroku_email: irina.gnativ@gmail.com
      - name: change heroku buildpack to python
        run: heroku buildpacks:set heroku/python
      - name: pulling from heroku
        run: git pull heroku master
      - name: deploy to prod backend
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: dashboard-for-errors
          heroku_email: irina.gnativ@gmail.com
          buildpack: "https://github.com/heroku/heroku-buildpack-python.git"
          appdir: "backend"
      - uses: actions/checkout@v2
      - name: bump version and push tag
        uses: anothrNick/github-tag-action@18284c78f6ac68868d5341f57c4f971fb5b7605c
        if: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
#      - name: slack notifications
#        uses: 8398a7/action-slack@v3
#        with:
#          status: ${{ job.status }}
#          fields: repo,commit,took,message,author
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#        if: always() # Pick up events even if the job fails or is canceled.
#      - name: health check
#        uses: jtalk/url-health-check-action@v1.5
#        with:
#          url: https://dashboard-for-errors.herokuapp.com
#          max-attempts: 3
#          retry-delay: 5s